package rop.miu.util;

public class ROPConstants {

	public static final short
				ACTIVATED = 0,
				DESACTIVATED = 1,
				DELETED = 2;

	public static final String
				DROIT_TOUT = "TOUT",
				DROIT_TOUT_SAUF = "TOUT_SAUF",
				DROIT_ACCEDER_ADMIN = "ACCEDER_ADMIN",
				DROIT_CONSULTER_COMPTES = "CONSULTER_COMPTES",
				DROIT_DEBITER_COMPTES = "DEBITER_COMPTES",
				DROIT_CREDITER_COMPTES = "CREDITER_COMPTES",
				DROIT_CREER_COMPTES = "CREER_COMPTES",
				DROIT_GELER_COMPTES = "GELER_COMPTES",
				DROIT_REALISER_TRANFERT = "REALISER_TRANFERT",
				DROIT_CONSULTER_OPERATION = "CONSULTER_OPERATION",
				DROIT_VALIDER_OPERATION = "VALIDER_OPERATION",
				DROIT_OPERATION_GENERALE = "OPERATION_GENERALE",
				
				DEBIT = "Debit",
				CREDIT = "Credit",
				
				DAO_FILE = "rop/miu/dao/dao.cfg.rop.xml";
}
