package rop.miu.util;

public class ROPConstants {

	public static final short
				STATE_ACTIVATED = 0,
				STATE_READ = 0,
				STATE_PUBLISHED = 0,
				STATE_ACCEPTED = 0,
				STATE_PROGRAMMED = 0,
				STATE_REVIEWED = 0,
				STATE_DESACTIVATED = 1,
				STATE_UNREAD = 1,
				STATE_UNPUBLISHED = 1,
				STATE_REFUSED = 1,
				STATE_COMPLETED = 1,
				STATE_NOT_REVIEWED = 1,
				STATE_TRASHED = 2,
				STATE_IN_REVIEW = 2,
				STATE_DELETED = 3,
				STATE_WAITING_CORRECTION = 3,
				STATE_WAITING_VALIDATION = 4,
				STATE_DRAFT = 4,
				STATE_SUBMITTED = 5;

	public static final String
				DROIT_TOUT = "TOUT",
				DROIT_TOUT_SAUF = "TOUT_SAUF",
				DROIT_ACCEDER_ADMIN = "ACCEDER_ADMIN",
				DROIT_CONSULTER_COMPTES = "CONSULTER_COMPTES",
				DROIT_DEBITER_COMPTES = "DEBITER_COMPTES",
				DROIT_CREDITER_COMPTES = "CREDITER_COMPTES",
				DROIT_CREER_COMPTES = "CREER_COMPTES",
				DROIT_GELER_COMPTES = "GELER_COMPTES",
				DROIT_REALISER_TRANFERT = "REALISER_TRANFERT",
				DROIT_CONSULTER_OPERATION = "CONSULTER_OPERATION",
				DROIT_VALIDER_OPERATION = "VALIDER_OPERATION",
				DROIT_OPERATION_GENERALE = "OPERATION_GENERALE",
				
				DEBIT = "Debit",
				CREDIT = "Credit",
				
				DAO_FILE = "rop/miu/dao/dao.cfg.rop.xml";
}
